# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a6c3a2a0cc512750395547b8c4f35a5e646f37c72f171aaf0c33391f50d5e2285d5cebd406d5ad746e6a8fd01407c49661dde0609054435fc1bc9aed75a71fd

test:
  secret_key_base: 45f62c734d7113f2b53c4bcde712ef7742a3f9425a06cac9d492899de1ead7d58212aa2f888f68a77b635c4956950f00ba768b3a3b8fab1b2466c899a308b3c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
